name: Deployment pipeline

on:
  push:
    branches:
      - master
  #pull_request:
  #  branches: [ master ]
  #  types: [ opened, syncronize ]
  # Actually we could separate deployment step to get this working (not making double messages to Slack), but we are just lazy.

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && contains( join(github.event.commits.*.message), '#skip' ) == false }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 'patch' # major.minor.patch
          WITH_V: true
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'

      - name: npm install
        run: npm install

      - name: lint
        run: npm run eslint

      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          quiet: false
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: 'http://localhost:5000'

      - name: Deploy to Heroku
        if: ${{ github.event_name == 'push' && contains( join(github.event.commits.*.message), '#skip' ) == false }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "emiselro-pokedex"
          heroku_email: "emil.selroos@gamil.com"
          healthcheck: "https://emiselro-pokedex.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true

      - name: Successful Deployment!
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: commit,author,took
          channel: '#code'
          custom_payload: |
            {
              icon_emoji: ':white_check_mark:',
              attachments: [{
                color: 'good',
                text: `Something deployed to https://github.com/emilselroos/FullStackOpen-pokedex/ (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR} \n Build took ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        if: ${{ success() }}

      - name: Failure on Deployment!
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,took
          icon_emoji: ':no_entry:'
          channel: '#code'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        if: ${{ failure() }}
          
