name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
    types: [ opened, syncronize ]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && contains( join(github.event.commits.*.message), '#skip' ) == false }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 'patch' # major.minor.patch
          WITH_V: true
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'

      - name: npm install
        run: npm install

      - name: lint
        run: npm run eslint

      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          quiet: false
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: 'http://localhost:5000'

      - name: Deploy to Heroku
        if: ${{ github.event_name == 'push' && contains( join(github.event.commits.*.message), '#skip' ) == false }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "emiselro-pokedex"
          heroku_email: "emil.selroos@gamil.com"
          healthcheck: "https://emiselro-pokedex.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true

      - name: On Success
        if: ${{ job.status == 'success' }}
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: "{\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Success! New deployment from https://github.com/emilselroos/FullStackOpen-pokedex/ to https://emiselro-pokedex.herokuapp.com/\"}}]}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        
      - name: On Failure
        if: ${{ job.status == 'failure' }}
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: "{\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Failure!\"}}]}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK


